### ISSUE TITLE
CwpSearchEngine doesn't properly filter for ShowInSearch

### ISSUE THREAD

**Issue by chillu** [silverstripe/cwp-search#23]
Steve: we've agreed to extend this to strict "outlet filtering" at a core level on all DataObjects

We'll do the work for this the main ShowInSearch issue https://github.com/silverstripe/silverstripe-fulltextsearch/issues/257

## PR
https://github.com/silverstripe/cwp-search/pull/31

---

Looking at the [searching dataobject](https://www.cwp.govt.nz/developer-docs/en/2/features/solr_search/searching_dataobjects/) docs, it tells you to use `addFilterField('ShowInSearch')` for your own custom objects in the index. In other sections of the docs, it [uses](https://www.cwp.govt.nz/developer-docs/en/2/features/solr_search/basic_usage/) `SolrIndex->search(). This ends up using [CwpSearchEngine](https://github.com/silverstripe/cwp-search/blob/master/src/CwpSearchEngine.php) through some dependency injection shenanigans. Which in turn adds this bit:

```php
$query->addExclude(SiteTree::class . '_ShowInSearch', 0);
```

`CwpSearchEngine` should be agnostic of models, yet it only filters out one particular model (`SiteTree`), causing other models to ignore this flag *unless* it's specifically added in a `SearchQuery` instance of a custom controller. Given that the CWP module specifically provides a [SearchControllerExtension](https://github.com/silverstripe/cwp-search/blob/master/src/Extensions/SearchControllerExtension.php) to avoid you getting to that level of implementation detail, I don't think we can rely on developers getting this right.

To make matters worse, we fixed *one* of these cases (`File`) in CWP 1.x already (see [pull request](https://github.com/silverstripe/cwp/pull/64/files)), but that never made it into CWP 2.x.  

The only saving bit here is that neither 3.x nor 4.x allowed configuring of `File.ShowInSearch` through the UI, so it's always set to `true`. Regardless, I think this is high priority to fix.

**Comment by robbieaverill** [comment]
So perhaps we can replace the line you've highlighted with a loop of the classes it's including in its query, check whether the model has a ShowInSearch field, and if so then add it as in the example.

I don't think we can add it for classes that don't have the field - I think that throws an error for non-existent fields.

**Comment by emteknetnz** [comment]
Have removed this incomplete functionality from cwp-search
https://github.com/silverstripe/cwp-search/pull/31/files#diff-7011a481b6b4ef6344368aa6e012065cL61

Instead now relying on filtering in fulltextsearch
https://github.com/silverstripe/silverstripe-fulltextsearch/pull/275/files#diff-d695e5490e29fe37593698a4d621ce5bR784
