### ISSUE TITLE
Issue when defining extra classes_to_search for SearchControllerExtension

### ISSUE THREAD

**Issue by jakxnz** [silverstripe/cwp-search#3]
*cwp/cwp-search 1.0.0-beta1*

```yml
CWP\Search\Extensions\SearchControllerExtension:
  classes_to_search:
    - class: SilverStripe\Assets\File
```

Results in error:

> [Unknown Error] exception 'ReflectionException' with message 'Class 1 does not exist' in /var/www/public/vendor/silverstripe/framework/src/Core/ClassInfo.php:227
> 
> Stack trace: 
> #0 /var/www/public/vendor/silverstripe/framework/src/Core/ClassInfo.php(227): ReflectionClass->__construct('1') 
> #1 /var/www/public/vendor/silverstripe/framework/src/Core/ClassInfo.php(250): SilverStripe\Core\ClassInfo::class_name(1) 
> #2 /var/www/public/vendor/silverstripe/fulltextsearch/src/Search/SearchIntrospection.php(43): SilverStripe\Core\ClassInfo::ancestry(1) 
> #3 /var/www/public/vendor/silverstripe/fulltextsearch/src/Search/SearchIntrospection.php(90): SilverStripe\FullTextSearch\Search\SearchIntrospection::hierarchy(1, true) 
> #4 /var/www/public/vendor/tractorcow/silverstripe-fluent/src/Search/FluentSearchVariant.php(28): SilverStripe\FullTextSearch\Search\SearchIntrospection::has_extension(1, 'TractorCow\\Flue...', true) 
> #5 /var/www/public/vendor/silverstripe/fulltextsearch/src/Search/Variants/SearchVariant.php(121): TractorCow\Fluent\Search\FluentSearchVariant->appliesTo(1, true) 
> #6 /var/www/public/vendor/silverstripe/fulltextsearch/src/Search/Variants/SearchVariant.php(196): SilverStripe\FullTextSearch\Search\Variants\SearchVariant::variants(1, true) 
> #7 /var/www/public/vendor/silverstripe/fulltextsearch/src/Solr/SolrIndex.php(857): SilverStripe\FullTextSearch\Search\Variants\SearchVariant::withCommon(Array) 
> #8 /var/www/public/vendor/silverstripe/fulltextsearch/src/Solr/SolrIndex.php(691): SilverStripe\FullTextSearch\Solr\SolrIndex->applySearchVariants(Object(SilverStripe\FullTextSearch\Search\Queries\SearchQuery)) 
> #9 /var/www/public/vendor/cwp/cwp-search/src/CwpSearchIndex.php(101): SilverStripe\FullTextSearch\Solr\SolrIndex->search(Object(SilverStripe\FullTextSearch\Search\Queries\SearchQuery), 0, 10, Array) 
> #10 /var/www/public/vendor/cwp/cwp-search/src/CwpSearchEngine.php(115): CWP\Search\CwpSearchIndex->search(Object(SilverStripe\FullTextSearch\Search\Queries\SearchQuery), 0, 10, Array) 
> #11 /var/www/public/vendor/cwp/cwp-search/src/CwpSearchEngine.php(139): CWP\Search\CwpSearchEngine->getResult('Keyword', Array, Object(OEC\Search\OECSearchIndex), 10, 0, true) 
> #12 /var/www/public/vendor/cwp/cwp-search/src/Extensions/SearchControllerExtension.php(117): CWP\Search\CwpSearchEngine->search('Keyword', Array, Object(OEC\Search\OECSearchIndex), 10, 0, true) 
> #13 [internal function]: CWP\Search\Extensions\SearchControllerExtension->results(Array, Object(SilverStripe\CMS\Search\SearchForm), Object(SilverStripe\Control\HTTPRequest), Object(SilverStripe\Forms\FormRequestHandler)) 
> #14 /var/www/public/vendor/silverstripe/framework/src/Core/Extensible.php(144): call_user_func_array(Array, Array) 
> #15 /var/www/public/vendor/silverstripe/framework/src/Core/CustomMethods.php(61): SilverStripe\View\ViewableData->SilverStripe\Core\{closure}(Object(CWP\Search\CwpSearchPageController), Array) 
> #16 /var/www/public/vendor/silverstripe/framework/src/Forms/FormRequestHandler.php(231): SilverStripe\View\ViewableData->__call('results', Array) 
> #17 /var/www/public/vendor/silverstripe/framework/src/Forms/FormRequestHandler.php(231): CWP\Search\CwpSearchPageController->results(Array, Object(SilverStripe\CMS\Search\SearchForm), Object(SilverStripe\Control\HTTPRequest), Object(SilverStripe\Forms\FormRequestHandler)) 
> #18 /var/www/public/vendor/silverstripe/framework/src/Control/RequestHandler.php(319): SilverStripe\Forms\FormRequestHandler->httpSubmission(Object(SilverStripe\Control\HTTPRequest)) 
> #19 /var/www/public/vendor/silverstripe/framework/src/Control/RequestHandler.php(201): SilverStripe\Control\RequestHandler->handleAction(Object(SilverStripe\Control\HTTPRequest), 'httpSubmission') 
> #20 /var/www/public/vendor/silverstripe/framework/src/Control/RequestHandler.php(225): SilverStripe\Control\RequestHandler->handleRequest(Object(SilverStripe\Control\HTTPRequest)) 
> #21 /var/www/public/vendor/silverstripe/framework/src/Control/Controller.php(212): SilverStripe\Control\RequestHandler->handleRequest(Object(SilverStripe\Control\HTTPRequest)) 
> #22 /var/www/public/vendor/silverstripe/cms/code/Controllers/ContentController.php(229): SilverStripe\Control\Controller->handleRequest(Object(SilverStripe\Control\HTTPRequest)) 
> #23 /var/www/public/vendor/silverstripe/framework/src/Control/Director.php(361): SilverStripe\CMS\Controllers\ContentController->handleRequest(Object(SilverStripe\Control\HTTPRequest)) 
> #24 /var/www/public/vendor/tractorcow/silverstripe-fluent/src/Middleware/DetectLocaleMiddleware.php(90): SilverStripe\Control\Director->SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #25 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): TractorCow\Fluent\Middleware\DetectLocaleMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #26 /var/www/public/vendor/tractorcow/silverstripe-fluent/src/Middleware/InitStateMiddleware.php(54): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #27 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): TractorCow\Fluent\Middleware\InitStateMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #28 /var/www/public/vendor/silverstripe/versioned/src/VersionedHTTPMiddleware.php(40): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #29 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Versioned\VersionedHTTPMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #30 /var/www/public/vendor/silverstripe/framework/src/Security/BasicAuthMiddleware.php(68): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #31 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\BasicAuthMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #32 /var/www/public/vendor/silverstripe/framework/src/Security/AuthenticationMiddleware.php(61): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #33 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\AuthenticationMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #34 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/CanonicalURLMiddleware.php(155): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #35 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #36 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/FlushMiddleware.php(26): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #37 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\FlushMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #38 /var/www/public/vendor/silverstripe/framework/src/Control/RequestProcessor.php(66): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #39 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\RequestProcessor->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #40 /var/www/public/vendor/silverstripe/hybridsessions/src/Control/HybridSessionMiddleware.php(18): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #41 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\HybridSessions\Control\HybridSessionMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #42 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/AllowedHostsMiddleware.php(60): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #43 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #44 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/TrustedProxyMiddleware.php(176): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #45 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #46 /var/www/public/vendor/cwp/cwp-core/src/Control/InitialisationMiddleware.php(53): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #47 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): CWP\Core\Control\InitialisationMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #48 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #49 /var/www/public/vendor/silverstripe/framework/src/Control/Director.php(370): SilverStripe\Control\Director->callMiddleware(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #50 /var/www/public/vendor/silverstripe/framework/src/Control/HTTPApplication.php(48): SilverStripe\Control\Director->handleRequest(Object(SilverStripe\Control\HTTPRequest)) 
> #51 [internal function]: SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #52 /var/www/public/vendor/silverstripe/framework/src/Control/HTTPApplication.php(66): call_user_func(Object(Closure), Object(SilverStripe\Control\HTTPRequest)) 
> #53 [internal function]: SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #54 /var/www/public/vendor/silverstripe/framework/src/Core/Startup/ErrorControlChainMiddleware.php(56): call_user_func(Object(Closure), Object(SilverStripe\Control\HTTPRequest)) 
> #55 [internal function]: SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(Object(SilverStripe\Core\Startup\ErrorControlChain)) 
> #56 /var/www/public/vendor/silverstripe/framework/src/Core/Startup/ErrorControlChain.php(236): call_user_func(Object(Closure), Object(SilverStripe\Core\Startup\ErrorControlChain)) 
> #57 /var/www/public/vendor/silverstripe/framework/src/Core/Startup/ErrorControlChain.php(226): SilverStripe\Core\Startup\ErrorControlChain->step() 
> #58 /var/www/public/vendor/silverstripe/framework/src/Core/Startup/ErrorControlChainMiddleware.php(69): SilverStripe\Core\Startup\ErrorControlChain->execute() 
> #59 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #60 /var/www/public/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) 
> #61 /var/www/public/vendor/silverstripe/framework/src/Control/HTTPApplication.php(67): SilverStripe\Control\HTTPApplication->callMiddleware(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) 
> #62 /var/www/public/vendor/silverstripe/framework/src/Control/HTTPApplication.php(49): SilverStripe\Control\HTTPApplication->execute(Object(SilverStripe\Control\HTTPRequest), Object(Closure), false) 
> #63 /var/www/public/index.php(26): SilverStripe\Control\HTTPApplication->handle(Object(SilverStripe\Control\HTTPRequest)) 
> #64 {main}

As far as I can tell, in SearchVariant::withCommon(), in the scope of
```
...
foreach ($classes as $class => $options) {
...
```
`$class` is the array index, which is just an `int`, derived from the yaml array.

This error doesn't present itself until there are at least two `classes_to_search`.

---

This does work:
```
CWP\Search\Extensions\SearchControllerExtension:
  classes_to_search:
    SilverStripe\Assets\File:
      class: SilverStripe\Assets\File
```

But it does not align with the CWP docs.

**Comment by robbieaverill** [comment]
Thanks for reporting! You're right in that the documentation needs to be updated to match the new expected data structure for `SearchVariant::withCommon`.

I'd like to see the input data structure here validated a bit more thoroughly in future, and also remove the unnecessary `class: MyClass` value (since it's the key now anyway), but that can wait for another time.

In the meantime, the fixes are at https://github.com/silverstripe/cwp/pull/66 and https://github.com/silverstripe/cwp-search/pull/5.
