### ISSUE TITLE
Index method  should be compatible with ...

### ISSUE THREAD

**Issue by adrexia** [silverstripe/cwp-search#30]
The index method on [CwpSearchPageController](https://github.com/silverstripe/cwp-search/blob/1/src/CwpSearchPageController.php#L36) conflicts with the scaffolding for the [RedirectorPageController](https://github.com/silverstripe/silverstripe-cms/blob/4/code/Model/RedirectorPageController.php#L20), meaning warnings are thrown when  index is overwritten on PageController as it is not possible to be compatible with both of these controllers.

**Comment by emteknetnz** [comment]
@adrexia so is what you're saying is that CwpSearchPageController should be changed to `public function index(HTTPRequest $request)`?

**Comment by adrexia** [comment]
Yes, I think that's the most direct solution

**Comment by dhensby** [comment]
@adrexia PR, please?

**Comment by adrexia** [comment]
Ahhh... I guess I could. I don't need it anymore, but it is a fairly minor fix.

**Comment by GuySartorelli** [comment]
Great idea but it's an old issue that we're not going to do anything with any time soon. Closing. If someone is keen for this and wants to put in the work to implement it, `@` me and we can revisit.
