### ISSUE TITLE
CMS 5 - Search url is wrong

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cwp-search#54]
Found as part of 5.0.0 beta testing

Searching for a search using the search term is missing the leading `/`, so the search does work

We probably just need to update SearchControllerExtension::SearchForm()

## Acceptance criteria
- Code is reviewed and updated to work with our new trailing slash configuration.
- Search works with and without trailing slashes.
- Turning off trailing slash redirect, doesn't break search.

## Failed test
[Search terms are matched](https://studio.cucumber.io/projects/301855/test-runs/748052/folder-snapshots/7887504/scenario-snapshots/27677676/test-snapshots/37761999)

### PRs
https://github.com/silverstripe/cwp-search/pull/56

**Comment by GuySartorelli** [comment]
PR merged.
